#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"

CYPRESS_BACKOFFICE_USERNAME="$(get-k8s-concourse-secret boclips e2e backoffice-username)"
CYPRESS_BACKOFFICE_PASSWORD="$(get-k8s-concourse-secret boclips e2e backoffice-password)"
CYPRESS_FRONTEND_USERNAME="$(get-k8s-concourse-secret boclips e2e frontend-username)"
CYPRESS_FRONTEND_PASSWORD="$(get-k8s-concourse-secret boclips e2e frontend-password)"
CYPRESS_OPERATOR_USERNAME="$(get-k8s-concourse-secret boclips operator testing-username)"
CYPRESS_OPERATOR_PASSWORD="$(get-k8s-concourse-secret boclips operator testing-password)"
CYPRESS_LTI_CONSUMER_KEY="$(get-k8s-concourse-secret boclips testing-lti consumer-key)"
CYPRESS_LTI_CONSUMER_SECRET="$(get-k8s-concourse-secret boclips testing-lti consumer-secret)"

export CYPRESS_BACKOFFICE_USERNAME
export CYPRESS_BACKOFFICE_PASSWORD
export CYPRESS_FRONTEND_USERNAME
export CYPRESS_FRONTEND_PASSWORD
export CYPRESS_OPERATOR_USERNAME
export CYPRESS_OPERATOR_PASSWORD
export CYPRESS_LTI_CONSUMER_KEY
export CYPRESS_LTI_CONSUMER_SECRET

fly --target ci \
    execute \
    --config "$cwd/pipelines/tasks/load-fixtures.yml" \
    --input source="$cwd"
