#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"

CYPRESS_BACKOFFICE_USERNAME="$(decoded-secret boclips.e2e concourse-main | jq -r '.["backoffice-username"]')"
CYPRESS_BACKOFFICE_PASSWORD="$(decoded-secret boclips.e2e concourse-main | jq -r '.["backoffice-password"]')"
CYPRESS_FRONTEND_USERNAME="$(decoded-secret boclips.e2e concourse-main | jq -r '.["frontend-username"]')"
CYPRESS_FRONTEND_PASSWORD="$(decoded-secret boclips.e2e concourse-main | jq -r '.["frontend-password"]')"
CYPRESS_OPERATOR_USERNAME="$(decoded-secret boclips.operator concourse-main | jq -r '.["testing-username"]')"
CYPRESS_OPERATOR_PASSWORD="$(decoded-secret boclips.operator concourse-main | jq -r '.["testing-password"]')"

export CYPRESS_BACKOFFICE_USERNAME
export CYPRESS_BACKOFFICE_PASSWORD
export CYPRESS_FRONTEND_USERNAME
export CYPRESS_FRONTEND_PASSWORD
export CYPRESS_OPERATOR_USERNAME
export CYPRESS_OPERATOR_PASSWORD

fly --target ci \
    execute \
    --config "$cwd/pipelines/tasks/run.yml" \
    --input source="$cwd" \
    --output test-results=test-results
