#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"

CYPRESS_BACKOFFICE_USERNAME="$(bo show credential concourse-main boclips.e2e backoffice-username)"
CYPRESS_BACKOFFICE_PASSWORD="$(bo show credential concourse-main boclips.e2e backoffice-password)"
CYPRESS_FRONTEND_USERNAME="$(bo show credential concourse-main boclips.e2e frontend-username)"
CYPRESS_FRONTEND_PASSWORD="$(bo show credential concourse-main boclips.e2e frontend-password)"
CYPRESS_OPERATOR_USERNAME="$(bo show credential concourse-main boclips.operator testing-username)"
CYPRESS_OPERATOR_PASSWORD="$(bo show credential concourse-main boclips.operator testing-password)"
CYPRESS_SELECTED_VIDEOS_TEST_USERNAME="$(bo show credential concourse-main boclips.e2e selected-videos-test-username)"
CYPRESS_SELECTED_VIDEOS_TEST_PASSWORD="$(bo show credential concourse-main boclips.e2e selected-videos-test-password)"
CYPRESS_LTI_CONSUMER_KEY="$(bo show credential concourse-main boclips.testing-lti consumer-key)"
CYPRESS_LTI_CONSUMER_SECRET="$(bo show credential concourse-main boclips.testing-lti consumer-secret)"

export CYPRESS_BACKOFFICE_USERNAME
export CYPRESS_BACKOFFICE_PASSWORD
export CYPRESS_FRONTEND_USERNAME
export CYPRESS_FRONTEND_PASSWORD
export CYPRESS_OPERATOR_USERNAME
export CYPRESS_OPERATOR_PASSWORD
export CYPRESS_SELECTED_VIDEOS_TEST_USERNAME
export CYPRESS_SELECTED_VIDEOS_TEST_PASSWORD
export CYPRESS_LTI_CONSUMER_KEY
export CYPRESS_LTI_CONSUMER_SECRET
export SPEC

fly --target ci \
    execute \
    --config "$cwd/pipelines/tasks/run.yml" \
    --input source="$cwd" \
    --output test-results=test-results
