#!/usr/bin/env bash

set -e

unknown=0

if [ "$#" -eq 2 ] && [ "$2" = "ci" ]
then
    cypress="npm run cypress:run"
else
    cypress="npm run cypress:open"
fi

if [ "$#" -eq 0 ] || [ $unknown -eq 1 ]
then
    read -p "Which environment to run against? " env
else
    env=$1
fi

case $env in
    [Ll]* )
        : ${CYPRESS_BACKOFFICE_BASE_URL:="http://localhost:3000"}
        : ${CYPRESS_BACKOFFICE_USERNAME:="$(lpass show e2e-backoffice-testing --username)"}
        : ${CYPRESS_BACKOFFICE_PASSWORD:="$(lpass show e2e-backoffice-testing --password)"}
        : ${CYPRESS_EDUCATORS_BASE_URL:="http://localhost:8081"}
        : ${CYPRESS_EDUCATORS_USERNAME:="$(lpass show e2e-educators-testing --username)"}
        : ${CYPRESS_EDUCATORS_PASSWORD:="$(lpass show e2e-educators-testing --password)"}
        export CYPRESS_BACKOFFICE_BASE_URL
        export CYPRESS_BACKOFFICE_USERNAME
        export CYPRESS_BACKOFFICE_PASSWORD
        export CYPRESS_EDUCATORS_BASE_URL
        export CYPRESS_EDUCATORS_USERNAME
        export CYPRESS_EDUCATORS_PASSWORD
        $cypress
        ;;
    [Tt]* )
        : ${CYPRESS_BACKOFFICE_BASE_URL:="https://backoffice.testing-boclips.com"}
        : ${CYPRESS_BACKOFFICE_USERNAME:="$(lpass show e2e-backoffice-testing --username)"}
        : ${CYPRESS_BACKOFFICE_PASSWORD:="$(lpass show e2e-backoffice-testing --password)"}
        : ${CYPRESS_EDUCATORS_BASE_URL:="https://educators.testing-boclips.com"}
        : ${CYPRESS_EDUCATORS_USERNAME:="$(lpass show e2e-educators-testing --username)"}
        : ${CYPRESS_EDUCATORS_PASSWORD:="$(lpass show e2e-educators-testing --password)"}
        export CYPRESS_BACKOFFICE_BASE_URL
        export CYPRESS_BACKOFFICE_USERNAME
        export CYPRESS_BACKOFFICE_PASSWORD
        export CYPRESS_EDUCATORS_BASE_URL
        export CYPRESS_EDUCATORS_USERNAME
        export CYPRESS_EDUCATORS_PASSWORD
        $cypress
        ;;
    [Ss]* )
        : ${CYPRESS_BACKOFFICE_BASE_URL:="https://backoffice.staging-boclips.com"}
        : ${CYPRESS_BACKOFFICE_USERNAME:="$(lpass show e2e-backoffice-staging --username)"}
        : ${CYPRESS_BACKOFFICE_PASSWORD:="$(lpass show e2e-backoffice-staging --password)"}
        : ${CYPRESS_EDUCATORS_BASE_URL:="https://educators.staging-boclips.com"}
        : ${CYPRESS_EDUCATORS_USERNAME:="$(lpass show e2e-educators-staging --username)"}
        : ${CYPRESS_EDUCATORS_PASSWORD:="$(lpass show e2e-educators-staging --password)"}
        export CYPRESS_BACKOFFICE_BASE_URL
        export CYPRESS_BACKOFFICE_USERNAME
        export CYPRESS_BACKOFFICE_PASSWORD
        export CYPRESS_EDUCATORS_BASE_URL
        export CYPRESS_EDUCATORS_USERNAME
        export CYPRESS_EDUCATORS_PASSWORD
        $cypress
        ;;
    * )
        echo "Please answer [l]ocal, [t]esting or [s]taging."
        unknown=1
        ;;
esac
