#!/usr/bin/env bash

produce_output () {
    mkdir -p source/cypress/{screenshots,videos}
    touch source/cypress/{screenshots,videos}/tar-avoid-empty-dir
    cd "source/cypress" || exit
    tar -cf ../../test-results/results.tar \
        screenshots/* \
        videos/*
}
trap produce_output EXIT

if  [[ -z $CYPRESS_BACKOFFICE_USERNAME \
    || -z $CYPRESS_BACKOFFICE_PASSWORD \
    || -z $CYPRESS_TEACHERS_USERNAME \
    || -z $CYPRESS_TEACHERS_PASSWORD \
    || -z $CYPRESS_FRONTEND_USERNAME \
    || -z $CYPRESS_FRONTEND_PASSWORD \
    ]]
then
    echo "Missing CYPRESS_* credentials"
    exit 1
fi

(
cd source || exit 1
npm ci || exit 1
./run t ci
)