#!/usr/bin/env bash

produce_output () {
    mkdir -p source/cypress/{screenshots,videos}
    touch source/cypress/{screenshots,videos}/tar-avoid-empty-dir
    cd "source/cypress" || exit
    tar -cf ../../test-results/results.tar \
        screenshots/* \
        videos/*
}
trap produce_output EXIT

if [[ -z $CYPRESS_USERNAME || -z $CYPRESS_PASSWORD ]]
then
    echo "You must set CYPRESS_USERNAME and CYPRESS_PASSWORD"
    exit 1
fi

(
cd source || exit 1
npm ci || exit 1
./run t ci
)