#!/usr/bin/env bash

produce_output () {
    mkdir -p source/cypress/{screenshots,videos}
    touch source/cypress/{screenshots,videos}/tar-avoid-empty-dir
    cd "source/cypress" || exit
    tar -cf ../../test-results/results.tar \
        screenshots/* \
        videos/*
}
trap produce_output EXIT

if  [[ -z $CYPRESS_BACKOFFICE_USERNAME \
    || -z $CYPRESS_BACKOFFICE_PASSWORD \
    || -z $CYPRESS_FRONTEND_USERNAME \
    || -z $CYPRESS_FRONTEND_PASSWORD \
    || -z $CYPRESS_OPERATOR_USERNAME \
    || -z $CYPRESS_OPERATOR_PASSWORD \
    ]]
then
    if  [[ -z $CYPRESS_BACKOFFICE_USERNAME ]]
    then
        echo "Missing CYPRESS_BACKOFFICE_USERNAME"
    fi

    if  [[ -z $CYPRESS_BACKOFFICE_PASSWORD ]]
    then
        echo "Missing CYPRESS_BACKOFFICE_PASSWORD"
    fi

    if  [[ -z $CYPRESS_FRONTEND_USERNAME ]]
    then
        echo "Missing CYPRESS_FRONTEND_USERNAME"
    fi

    if  [[ -z $CYPRESS_FRONTEND_PASSWORD ]]
    then
        echo "Missing CYPRESS_FRONTEND_PASSWORD"
    fi

    if  [[ -z $CYPRESS_OPERATOR_USERNAME ]]
    then
        echo "Missing CYPRESS_OPERATOR_USERNAME"
    fi

    if  [[ -z $CYPRESS_OPERATOR_PASSWORD ]]
    then
        echo "Missing CYPRESS_OPERATOR_PASSWORD"
    fi

    exit 1
fi

(
cd source || exit 1

npm audit || exit 1

npm ci || exit 1

./run t ci
)