module.exports = {
  VIDEO_SERVICE_URL: process.env.CYPRESS_VIDEOSERVICE_BASE_URL,
  OPERATOR_USERNAME: process.env.CYPRESS_OPERATOR_USERNAME,
  OPERATOR_PASSWORD: process.env.CYPRESS_OPERATOR_PASSWORD,
  TOKEN_URL: process.env.CYPRESS_TOKEN_URL
};
